export const FETCH_LATEST_INCIDENTS = "FETCH_LATEST_INCIDENTS";
export const FETCH_LATEST_INCIDENTS_SUCCEEDED =
	"FETCH_LATEST_INCIDENTS_SUCCEEDED";
export const INCIDENTS_FETCH_FAILED = "INCIDENTS_FETCH_FAILED";
